services:
  rabbit:
    image: rabbitmq:3.12-management
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
    networks:
      - kd17msbank
  configserver:
    image: "kd17exe/configserver:cs2"
    container_name: configserver-ms
    ports:
      - "8071:8071"
    depends_on:
      rabbit:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent http://localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    deploy:
      resources:
        limits:
          memory: 1000m
    networks:
      - kd17msbank
    environment:
      SPRING_RABBITMQ_HOST: "rabbit"
      SPRING_RABBITMQ_PORT: "5672"
  account:
    image: "kd17exe/account:a2"
    container_name: account-ms
    ports:
      - "8081:8081"
    depends_on:
      configserver:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 700m
#till now it will work independently but for intercommunication we need to describe "network" in same position of deploy.
    networks:
      - kd17msbank
    environment:
      SPRING_APPLICATION_NAME: "account"
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/" #prefix should be always configserver but domain is a service name
      SPRING_PROFILES_ACTIVE: qa
      SPRING_RABBITMQ_HOST: "rabbit"
  cards:
    image: "kd17exe/cards:c2"
    container_name: cards-ms
    ports:
      - "8082:8082"
    depends_on:
      configserver:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - kd17msbank
    environment:
      SPRING_APPLICATION_NAME: "cards"
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/" #prefix should be always configserver but domain is a service name
      SPRING_PROFILES_ACTIVE: qa
      SPRING_RABBITMQ_HOST: "rabbit"
networks:
  kd17msbank:
    driver: "bridge"